# Automatically generated by configure - do not modify
SRC_PATH=/Users/yiannigiannaris/Documents/School/6.828/qemu/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
